services:
  db:
    image: mysql:8.0
    container_name: gdip-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gdip
    ports:
      - "3307:3306"
    volumes:
      - gdip_mysql_data:/var/lib/mysql

volumes:
  gdip_mysql_data: